[package]
name = "klayout-connect"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
description = "Connectivity extraction → Netlist IR for klayout-rs"

[dependencies]
klayout-core = { path = "../klayout-core", version = "0.0.1" }
klayout-geom = { path = "../klayout-geom", version = "0.0.1" }
smol_str = { workspace = true }

[lints]
workspace = true
