//! CDL (Circuit Description Language) writer — a SPICE subset used as
//! the layout-side input to LVS comparison.
//!
//! v1 emits a flat netlist with one subcircuit:
//!
//! ```text
//! * generated by klayout-connect
//! .SUBCKT TOP <pin1> <pin2> ...
//! * net <name>: shapes [bbox=...]
//! * (no devices yet — device extraction is a follow-up)
//! .ENDS TOP
//! ```
//!
//! Devices and instance hierarchy will be added once `klayout-connect`
//! supports device extraction. For now, the writer is the smallest
//! useful artifact: a list of nets with their bboxes, useful for
//! sanity-checking connectivity output and as a template for downstream
//! LVS comparison.

use crate::netlist::Netlist;
use std::path::Path;

impl Netlist {
    /// Write a CDL `.SUBCKT TOP ... .ENDS TOP` block. `pin_nets` lists
    /// the names of nets that should appear as subckt pins (in order);
    /// other nets are internal (commented).
    pub fn to_cdl(&self, subckt_name: &str, pin_nets: &[&str]) -> String {
        let mut out = String::new();
        out.push_str("* CDL netlist generated by klayout-connect\n");
        out.push_str(&format!(".SUBCKT {}", subckt_name));
        for p in pin_nets {
            out.push(' ');
            out.push_str(p);
        }
        out.push('\n');

        for net in self.nets() {
            let is_pin = pin_nets.iter().any(|p| *p == net.name);
            let prefix = if is_pin { "*  pin" } else { "*  net" };
            out.push_str(&format!(
                "{} {}: bbox=[{},{} {},{}], {} shapes\n",
                prefix,
                net.name,
                net.bbox.min.x,
                net.bbox.min.y,
                net.bbox.max.x,
                net.bbox.max.y,
                net.shapes.len(),
            ));
        }
        // Devices placeholder — populated when device extraction lands.
        out.push_str("* devices: (none — extraction not yet implemented)\n");
        out.push_str(&format!(".ENDS {}\n", subckt_name));
        out
    }

    pub fn save_cdl(
        &self,
        subckt_name: &str,
        pin_nets: &[&str],
        path: impl AsRef<Path>,
    ) -> std::io::Result<()> {
        std::fs::write(path, self.to_cdl(subckt_name, pin_nets))
    }
}
