[package]
name = "klayout-lef"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
description = "LEF/DEF reader and writer for klayout-rs (digital flow handoff)"

[dependencies]
klayout-core = { path = "../klayout-core", version = "0.0.1" }
smol_str = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
