[package]
name = "klayout-place"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
description = "Placement (global/legalize/detailed) for klayout-rs"

[dependencies]
klayout-core = { path = "../klayout-core", version = "0.0.1" }
smol_str = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[lints]
workspace = true

[[bench]]
name = "quadratic"
harness = false
