[package]
name = "klayout-liberty"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
description = "Liberty (.lib) timing-library reader for klayout-rs"

[dependencies]
klayout-core = { path = "../klayout-core", version = "0.0.1" }
smol_str = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
