//! Combinatorial `density_window` parity: every case was generated by
//! `python validation/oracle.py drc_density_grid` using KLayout's
//! `TilingProcessor` (same script as Ruby `with_density` / `without_density`).
//!
//! Regenerate after changing density-window logic or expanding the grid
//! definition in `oracle.py`.

use klayout_validate::corpus_path;

include!("drc_support.inc");

fn load_grid() -> DrcCorpus {
    let path = corpus_path("drc_density_grid.json");
    let bytes = std::fs::read(&path).unwrap_or_else(|e| {
        panic!(
            "missing {}: {e}\nrun: python validation/oracle.py drc_density_grid",
            path.display()
        )
    });
    serde_json::from_slice(&bytes).expect("invalid drc_density_grid corpus JSON")
}

#[test]
fn density_window_grid_matches_klayout() {
    let c = load_grid();
    for case in &c.cases {
        assert_eq!(
            case.rule, "density_window",
            "grid corpus must be density_window-only, got {:?}",
            case.rule
        );
        let label = format!("[{}/{}]", case.rule, case.name);
        let a = region_from_rects(&case.rects_a);
        let b = region_from_rects(&case.rects_b);
        let got = apply_drc_case(case, &a, &b);
        assert_region_eq(&label, &got, &case.result);
    }
    eprintln!(
        "{} density grid cases match KLayout {}",
        c.cases.len(),
        c.klayout_version
    );
}
