//! Liberty (.lib) parser parity vs OpenSTA.
//!
//! Corpus is regenerated by `validation/oracle_external.py liberty`,
//! which loads each `.lib` via OpenSTA inside a Docker container and
//! dumps cell area + pin direction/capacitance as canonical JSON.
//! This test loads the same `.lib` with our parser, projects it into
//! the same JSON shape, and asserts byte-equality.

use klayout_liberty::{parse_liberty_path, types::PinDirection};
use klayout_validate::corpus_path;
use serde_json::{json, Value};

const FIXTURES: &[&str] = &[
    "inv_buf",
    "two_input",
    "ff_simple",
    "complex_gates",
    "multi_output",
    "inout_pins",
];

fn dump_to_json(path: &std::path::Path) -> Value {
    let lib = parse_liberty_path(path)
        .unwrap_or_else(|e| panic!("parse {} failed: {e}", path.display()));
    let mut cells: Vec<Value> = lib
        .cells
        .iter()
        .map(|c| {
            let mut pins: Vec<Value> = c
                .pins
                .iter()
                .map(|p| {
                    let dir = p.direction.map(|d| match d {
                        PinDirection::Input => "input",
                        PinDirection::Output => "output",
                        // OpenSTA's TCL get_property returns "bidirect"
                        // for the Liberty `direction : inout` keyword.
                        PinDirection::Inout => "bidirect",
                        PinDirection::Internal => "internal",
                    });
                    json!({
                        "name": p.name.as_str(),
                        "direction": dir,
                        // OpenSTA reports cap=0.0 for output pins that
                        // don't declare one explicitly. Match that.
                        "cap": p.capacitance.unwrap_or(0.0),
                    })
                })
                .collect();
            pins.sort_by(|a, b| {
                a["name"].as_str().unwrap().cmp(b["name"].as_str().unwrap())
            });
            json!({
                "name": c.name.as_str(),
                "area": c.area,
                "pins": pins,
            })
        })
        .collect();
    cells.sort_by(|a, b| {
        a["name"].as_str().unwrap().cmp(b["name"].as_str().unwrap())
    });
    json!({ "cells": cells })
}

#[test]
fn liberty_parser_matches_opensta() {
    for name in FIXTURES {
        let lib_path = corpus_path(&format!("liberty/{name}.lib"));
        let json_path = corpus_path(&format!("liberty/{name}.json"));
        if !lib_path.exists() || !json_path.exists() {
            eprintln!(
                "skipping liberty::{name}: corpus missing.\n\
                 Regenerate with: python validation/oracle_external.py liberty"
            );
            return;
        }
        let got = dump_to_json(&lib_path);
        let exp_bytes = std::fs::read(&json_path).expect("read json");
        let expected: Value = serde_json::from_slice(&exp_bytes).expect("parse json");
        if got != expected {
            let g = serde_json::to_string_pretty(&got).unwrap();
            let e = serde_json::to_string_pretty(&expected).unwrap();
            panic!("liberty::{name} mismatch\n--- got ---\n{g}\n\n--- expected (OpenSTA) ---\n{e}\n");
        }
    }
}
